# Generated by Django 4.1.3 on 2023-12-20 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_remove_folder_note'),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folder.folder', verbose_name='Notun Ait Olduğu Klasör'),
        ),
    ]
