# Generated by Django 4.1.3 on 2023-12-21 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import visual_note.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Günlüğün Oluşturulma Tarihi')),
                ('baslik', models.CharField(max_length=300, verbose_name='Günlük Basligi')),
                ('note', models.TextField(verbose_name='Günlük Açıklaması')),
                ('image', models.ImageField(blank=True, null=True, upload_to=visual_note.utils.get_upload_path)),
                ('reminder_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Günlüğün Ait Olduğu Kullanıcı')),
            ],
        ),
    ]
